<a href="https://colab.research.google.com/github/onleey/pandas_demo/blob/master/400_pandas_%EA%B8%B0%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Version

In [ ]:
#python
import sys
print(sys.version)


!python --version


3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Python 3.10.12


In [ ]:
#numpy
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
#pandas
import pandas as pd
print(pd.__version__)

1.5.3


In [ ]:
#google colab
!pip freeze

absl-py==1.4.0
aiohttp==3.8.6
aiosignal==1.3.1
alabaster==0.7.13
albumentations==1.3.1
altair==4.2.2
anyio==3.7.1
appdirs==1.4.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
array-record==0.5.0
arviz==0.15.1
astropy==5.3.4
astunparse==1.6.3
async-timeout==4.0.3
atpublic==4.0
attrs==23.1.0
audioread==3.0.1
autograd==1.6.2
Babel==2.13.1
backcall==0.2.0
beautifulsoup4==4.11.2
bidict==0.22.1
bigframes==0.13.0
bleach==6.1.0
blinker==1.4
blis==0.7.11
blosc2==2.0.0
bokeh==3.3.1
bqplot==0.12.42
branca==0.7.0
build==1.0.3
CacheControl==0.13.1
cachetools==5.3.2
catalogue==2.0.10
certifi==2023.7.22
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
chex==0.1.7
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
cloudpickle==2.2.1
cmake==3.27.7
cmdstanpy==1.2.0
colorcet==3.0.1
colorlover==0.3.0
colour==0.1.5
community==1.0.0b1
confection==0.1.3
cons==0.4.6
contextlib2==21.6.0
contourpy==1.2.0
cryptography==41.0.5
cufflinks==0.17.3
cupy-cuda11x==11.0.0
cvxopt==1.3.2
cvxpy==1.3.2
cycler==0.12.1
cy

## 구글 드라이브 연동

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

%cd '/content/drive/MyDrive/001'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/001


## 파일 형식 데이터 불러오기


In [ ]:
print(type(pd))
print(dir(pd))

<class 'module'>
['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__deprecated_num_index_names', '__dir__', '__doc__', '__docformat__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_config', '_is_numpy_dev', '_libs', '_testing', '_typing', '_version', 'annotations', 'api', 'arra

In [ ]:
# header 키워드를 지정하지않고 호출했을때는 무조건 파일의 첫줄을 header로 처리한다.
data = pd.read_csv('./001_1/num.txt')
print(data)

   1  2  3  4   5
0  6  7  8  9  10


In [ ]:
#읽어올 파일에 header가 없으면 header = None을 지정한다.
# 그렇지 않으면 첫번째 줄을 컬럼명으로 처리한다.
# header 파라미터의 default : 'infer' 이다.
data = pd.read_csv('./001_1/num.txt', header=None)
print(data)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10


In [ ]:
print(type(data))     #pandas.core.frame.dataframe
print(dir(data))

<class 'pandas.core.frame.DataFrame'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__

In [ ]:
print(data[0])         # data.[ 컬럼명 (열)]
print(type(data[0]))   #'pandas.core.series.Series
print(dir(data[0]))

0    1
1    6
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__r

In [ ]:
print(data.iloc[0])         # data. iloc[index(행)]
print(type(data.iloc[0]))   #pandas.core.series.Series


0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
# numpy
a = np.arange(1,13). reshape(3,4)
print(type(a))
print(a)
print(a[1][2])           # a[행][열]
print(a[1,2])            # a[행,열]

<class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
7


In [ ]:
#list
b = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print(type(b))
print(b)
print(b[1][2])   #list에서 슬라이싱, boolean indexing, fancy indexing 안됨


<class 'list'>
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
7


In [ ]:
print(data)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10


In [ ]:
#.values() 하면 numpy 포맷으로 변환한다.
# 내부적으로 numpy로 되어있기 때문에 가능하다.
print(data.values)
print(type(data.values))   #numpy.ndarray 배열임

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [ ]:
#'__array__' 가 있으면 numpy와 호환된다.
print(dir(data))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul_

###웹 주소에서 데이터 불러오기

In [ ]:
#header는 기본이 첫줄을 컬럼명으로 가져오도록 설정이 되어있기 때문에 header = 'infer' 생략가능 ㅑ
data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv',header='infer')
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# 전반적인 데이터 정보 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
#기본적으로 앞의 5개를 보여줌
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.head(10)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [ ]:
#제일 아래에서 5개를 보여줌
data.tail()


total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.tail(10)

total_bill   tip     sex smoker   day    time  size
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.sample()   #아무거나 랜덤으로 1개씩 보여줌

total_bill   tip   sex smoker   day   time  size
126        8.52  1.48  Male     No  Thur  Lunch     2

In [ ]:
data.sample(3)  #아무거나 랜덤으로 ()의 숫자만큼 보여줌

total_bill   tip     sex smoker   day    time  size
66        16.45  2.47  Female     No   Sat  Dinner     2
196       10.34  2.00    Male    Yes  Thur   Lunch     2
155       29.85  5.14  Female     No   Sun  Dinner     5

In [ ]:
#데이터만 가지고 옴
data.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [ ]:
#index만 가지고 옴
data.index

RangeIndex(start=0, stop=244, step=1)

In [ ]:
#column만 가지고 옴
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
#dict 타입
dicdata={'name':'홍길동','age':30}

print(dicdata['name'])  #정상처리 홍길동
#print(dicdata.name)    # 오류발생 AttributeError: 'dict' object has no attribute 'name'

홍길동


In [ ]:
print(dir(dict))
print(dict.items)
print(dicdata.items())

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']
<method 'items' of 'dict' objects>
dict_items([('name', '홍길동'), ('age', 30)])


In [ ]:
#pandas는 dictionary와 attribute 방식 모두 사용할 수 있다.
#dictionary 방식 이용
print(data['tip'])

#attribute 방식 이용
print(data.tip)

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64


In [ ]:
# data[열] 이므로 열의 fancying indexing을 사용 할 수 있다.
#컬럼을 fancying index를 이용해서 가져올 수 있으나, 행을 이용해서가져올 수 없다.
print(data[['tip','day']])    #정상처리
print('----------------------')
#keyError
#print(data[[0,2]])   -> 열을 지정

#data.iloc[행] 이므로 fancing indexing이 가능하다.
print(data.iloc[[0,2]])   #-> 행을지정   #정상처리

      tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]
----------------------
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
2       21.01  3.50    Male     No  Sun  Dinner     3


In [ ]:
#TypeError: cannot do slice indexing on RangeIndex with these indexers [1] of type str
# 컬럼을 slicing을 이용해서 가져올 수 없다.
#print(data['tip':'day'])

#row를 slicing을 이용해서 가져올 수 있다.
print(data[1:3]) #슬라이싱할때는 앞자리가 행으로 변함

   total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3


하나의 컬럼 또는 행을 가져오면 Series를 리턴한다.   
fancy indexing 을 이용해서 하나의 컬럼 또는 행을 가져오면 daraframe으로 리턴한다.   

In [ ]:
print(type(data.iloc[3]))
print('----------------------')
print(data.iloc[3])
print('----------------------')
print(type(data['tip']))
print('----------------------')
print(data['tip'])

<class 'pandas.core.series.Series'>
----------------------
total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object
----------------------
<class 'pandas.core.series.Series'>
----------------------
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64


In [ ]:
print(data.iloc[2])

total_bill     21.01
tip              3.5
sex             Male
smoker            No
day              Sun
time          Dinner
size               3
Name: 2, dtype: object


In [ ]:
#data[['tip','day']]   #data frame 타입을 리턴
print(data.iloc[1:3])        #data frame 타입으로 리턴
print('---------------------------------------------')
data.iloc[1:3,:]


   total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3
---------------------------------------------


total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3

In [ ]:
data.iloc[0:5,1:3]            #data.iloc[행index, 열index]

tip     sex
0  1.01  Female
1  1.66    Male
2  3.50    Male
3  3.31    Male
4  3.61  Female

In [ ]:
print(data. iloc[[0,3,5],[1,3,4]])
# print(data.iloc[[0,3,5]],[[1,3,4]]) 이건 안됨.

    tip smoker  day
0  1.01     No  Sun
3  3.31     No  Sun
5  4.71     No  Sun
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
3       23.68  3.31    Male     No  Sun  Dinner     2
5       25.29  4.71    Male     No  Sun  Dinner     4 [[1, 3, 4]]


In [ ]:
print(data.iloc[3][1])  # 3행 1열의 data값을 가지고 오라
print(data.iloc[3,1])    # 3행 1열

3.31
3.31


In [ ]:
#data.sample(5)
data.head(2)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

iloc는 번호를 이용해서 가져오고, loc는 이름을이용해서 가지고 온다.

In [ ]:
data.loc[0,'tip']             #data.loc[행이름,열이름]

1.01

In [ ]:
data.iloc[0,1]  # data.iloc [행번호, 열번호]

1.01

In [ ]:
# data['tip', 0] 반대로는 사용못함
data['tip'][0]  # data[열이름][행이름]

1.01

In [ ]:
data.loc[0:3, 'tip':'day']

tip     sex smoker  day
0  1.01  Female     No  Sun
1  1.66    Male     No  Sun
2  3.50    Male     No  Sun
3  3.31    Male     No  Sun

In [ ]:
data.iloc[0:4, 1:5]

tip     sex smoker  day
0  1.01  Female     No  Sun
1  1.66    Male     No  Sun
2  3.50    Male     No  Sun
3  3.31    Male     No  Sun

In [ ]:
data.loc[[0,3,5],['tip','day','time']]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

In [ ]:
data.iloc[[0,3,5],[1,4,5]]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

## at
이름으로 한 위치의 값만 가지고 온다.

In [ ]:
print(data.at[0,'tip'])
print(data.loc[0,'tip'])
print(data.iloc[0,1])
print(data['tip'][0])

#print(data.at[0]['tip'])  # 안됨.
print(data.loc[0]['tip'])
print(data.iloc[0][1])
print('---------------------------------------------')
print(data['tip']) # 열 (이름)
print('---------------------------------------------')
print(data[3:5])   #행 (번호)


1.01
1.01
1.01
1.01
1.01
1.01
---------------------------------------------
0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64
---------------------------------------------
   total_bill   tip     sex smoker  day    time  size
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4


In [ ]:
#at 은 slicing을 사용 할 수 없다. #InvalidIndexError
data.at[0:3,'tip']

In [ ]:
#at 은 fancy indexing 을 사용 할 수 없다.
#InvalidIndexError
data.at[[0,1,5],'tip']

In [ ]:
#열일때
#data[['tip','day']] #ok
#data['tip':'day'] #타입에러

#행일때
data[0:5]  # ok
#data[[0,1,3]] #키에러

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4